language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - typings
deploy:
  provider: npm
  email: dave@etianen.com
  api_key:
    secure: # TODO
  skip_cleanup: true
  on:
    tags: true
    repo: etianen/js-base-error
notifications:
  on_success: never
  on_failure: change
